{
 "title": "Observability",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_server_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Web Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "16833ae1", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "dice-ruby" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"dice-ruby\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Web Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"web\"} |= `` | logfmt"
    }
   ]
  },
  {
   "title": "Sidekiq Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"sidekiq\"} |= `` | logfmt"
    }
   ]
  },
  {
   "title": "Sidekiq Webhooks Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"sidekiq_webhooks\"} |= `` | logfmt"
    }
   ]
  }
 ]
}