services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  redis_sidekiq:
    image: redis
    container_name: redis_sidekiq
    ports:
      - '6380:6379'

  redis_sidekiq_webhooks:
    image: redis
    container_name: redis_sidekiq_webhooks
    ports:
      - '6390:6379'

  web:
    build: ./
    container_name: web
    command: rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/rails-sidekiq
    depends_on:
      - redis
    environment:
      - REDIS_PROTOCOL=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=3
      - REDIS_SIDEKIQ_HOST=redis_sidekiq
      - REDIS_SIDEKIQ_PORT=6379
      - REDIS_SIDEKIQ_DB=3
    stdin_open: true
    tty: true

  sidekiq:
    build: ./
    container_name: sidekiq
    depends_on:
      - redis_sidekiq
    volumes:
      - .:/rails-sidekiq
    command: bundle exec sidekiq
    environment:
      - REDIS_PROTOCOL=redis
      - REDIS_SIDEKIQ_HOST=redis_sidekiq
      - REDIS_SIDEKIQ_PORT=6379
      - REDIS_SIDEKIQ_DB=3
    stdin_open: true
    tty: true

  sidekiq_webhooks:
    build: ./
    container_name: sidekiq_webhooks
    depends_on:
      - redis_sidekiq_webhooks
    volumes:
      - .:/rails-sidekiq
    command: bundle exec sidekiq -C config/sidekiq_webhooks.yml
    environment:
      - REDIS_PROTOCOL=redis
      - REDIS_SIDEKIQ_HOST=redis_sidekiq_webhooks
      - REDIS_SIDEKIQ_PORT=6379
      - REDIS_SIDEKIQ_DB=3
    stdin_open: true
    tty: true


