receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:  # Add a traces pipeline
      receivers: [otlp]
      exporters: [otlp, debug]  # You can use Jaeger, Zipkin, or another trace exporter instead of logging
